name: Flask app Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/

        strategy:
            matrix:
                python-version: [3.10]

        env:
            MODE: 'dev'

        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{matrix.python-version}}

            - name: Install dependencies
              run: python -m pip install --upgrade pip
                  pip install -r ../requirements.txt

            - name: Start Flask app
              run: flask run

            - name: Test app code
              run: python -m pytest
