name: Flask app Test

on:
    pull_resquest:
        branches:
            - main
jods:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/

        strategy:
            matrix:
                python-version: [3.10]

        env:
            MODE: "dev"

        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{matrix.python-version}}

            - name: install dependencies
              run: |
              python -m pip install --upgrade pip
              pip install -r ../requiment.txt

            - name: Test app code
              run: python ./main_test.py
